kitchen/urls.py
from django.urls import path

from kitchen.views import (
    index,
    CookListView,
    CookDetailView,
    CookCreateView,
    CookDeleteView,
    DishTypeListView,
    DishListView,
    DishTypeDetailView,
    DishTypeCreateView,
    DishTypeUpdateView,
    DishTypeDeleteView,
    DishDetailView,
    DishCreateView,
    DishUpdateView,
    DishDeleteView,
    ToggleAssignToDish,
)

urlpatterns = [
    path("", index, name="index"),
    path(
        "cooks/",
        CookListView.as_view(),
        name="cook-list",
    ),
    path(
        "cooks/<int:pk>/",
        CookDetailView.as_view(),
        name="cook-detail",
    ),
    path(
        "registration/",
        CookCreateView.as_view(),
        name="registration",
    ),
    path(
        "cooks/<int:pk>/delete/",
        CookDeleteView.as_view(),
        name="cook-delete",
    ),
    path(
        "dish-types/",
        DishTypeListView.as_view(),
        name="dish-type-list",
    ),
    path(
        "dish-types/<int:pk>/",
        DishTypeDetailView.as_view(),
        name="dish-type-detail",
    ),
    path(
        "dish-types/create/",
        DishTypeCreateView.as_view(),
        name="dish-type-create",
    ),
    path(
        "dish-types/<int:pk>/update/",
        DishTypeUpdateView.as_view(),
        name="dish-type-update",
    ),
    path(
        "dish-types/<int:pk>/delete/",
        DishTypeDeleteView.as_view(),
        name="dish-type-delete",
    ),
    path(
        "dishes/",
        DishListView.as_view(),
        name="dish-list",
    ),
    path(
        "dishes/<int:pk>/",
        DishDetailView.as_view(),
        name="dish-detail",
    ),
    path(
        "dishes/create/",
        DishCreateView.as_view(),
        name="dish-create",
    ),
    path(
        "dishes/<int:pk>/update/",
        DishUpdateView.as_view(),
        name="dish-update",
    ),
    path(
        "dishes/<int:pk>/delete/",
        DishDeleteView.as_view(),
        name="dish-delete",
    ),
    path(
        "dishes/<int:pk>/toggle-assign-to-dish/",
        ToggleAssignToDish.as_view(),
        name="toggle-assign-to-dish",
    )
]

app_name = "kitchen"

kitchen_service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path("admin/", admin.site.urls),
                  path("", include("kitchen.urls", namespace="kitchen")),
                  path("__debug__/", include("debug_toolbar.urls")),
                  path("accounts/", include("django.contrib.auth.urls")),
              ] + static(
    settings.STATIC_URL,
    document_root=settings.STATIC_ROOT
)

templates/includes/footer.html
<footer class="footer">
  <div class="copy">&copy; 2023 Developer</div>
  <div class="bottom-links">
    <div class="links">
      <span class="footer-text">More Info:</span>
      <a href="#" class="footer-text">Home</a>
      <a href="#" class="footer-text">About</a>
      <a href="#" class="footer-text">Contact</a>
    </div>
  </div>
</footer>

templates/includes/header.html
<header class="header">
  <a href="{% url "kitchen:index" %}" class="logo">Kitchen-Service</a>
  <nav class="nav-items">
    {% if user.is_authenticated %}
      <a href="{% url "kitchen:cook-list" %}">Cooks</a>
      <a href="{% url "kitchen:dish-list" %}">Dishes</a>
      <a href="{% url "kitchen:dish-type-list" %}">Dish Types</a>
      <a href="{% url "logout" %}">Logout</a>
      <a href="{% url "kitchen:cook-detail" pk=user.id %}">User:{{ user.username }}</a>
    {% else %}
      <a href="{% url "login" %}">Login</a>
    {% endif %}
  </nav>
</header>

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/search.html
{% load crispy_forms_filters %}

<form action="" method="get" class="form-inline">
  {{ search_form|crispy }}
  <input class="btn btn-default" type="submit" value="🔎">
</form>