kitchen/urls.py
from django.urls import path

from kitchen.views import (
    index,
    CookListView,
    CookDetailView,
    CookCreateView,
    CookDeleteView,
    DishTypeListView,
    DishListView,
    DishTypeDetailView,
    DishTypeCreateView,
    DishTypeUpdateView,
    DishTypeDeleteView,
    DishDetailView,
    DishCreateView,
    DishUpdateView,
    DishDeleteView,
    ToggleAssignToDish,
)

urlpatterns = [
    path("", index, name="index"),
    path(
        "cooks/",
        CookListView.as_view(),
        name="cook-list",
    ),
    path(
        "cooks/<int:pk>/",
        CookDetailView.as_view(),
        name="cook-detail",
    ),
    path(
        "registration/",
        CookCreateView.as_view(),
        name="registration",
    ),
    path(
        "cooks/<int:pk>/delete/",
        CookDeleteView.as_view(),
        name="cook-delete",
    ),
    path(
        "dish-types/",
        DishTypeListView.as_view(),
        name="dish-type-list",
    ),
    path(
        "dish-types/<int:pk>/",
        DishTypeDetailView.as_view(),
        name="dish-type-detail",
    ),
    path(
        "dish-types/create/",
        DishTypeCreateView.as_view(),
        name="dish-type-create",
    ),
    path(
        "dish-types/<int:pk>/update/",
        DishTypeUpdateView.as_view(),
        name="dish-type-update",
    ),
    path(
        "dish-types/<int:pk>/delete/",
        DishTypeDeleteView.as_view(),
        name="dish-type-delete",
    ),
    path(
        "dishes/",
        DishListView.as_view(),
        name="dish-list",
    ),
    path(
        "dishes/<int:pk>/",
        DishDetailView.as_view(),
        name="dish-detail",
    ),
    path(
        "dishes/create/",
        DishCreateView.as_view(),
        name="dish-create",
    ),
    path(
        "dishes/<int:pk>/update/",
        DishUpdateView.as_view(),
        name="dish-update",
    ),
    path(
        "dishes/<int:pk>/delete/",
        DishDeleteView.as_view(),
        name="dish-delete",
    ),
    path(
        "dishes/<int:pk>/toggle-assign-to-dish/",
        ToggleAssignToDish.as_view(),
        name="toggle-assign-to-dish",
    )
]

app_name = "kitchen"

kitchen_service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path("admin/", admin.site.urls),
                  path("", include("kitchen.urls", namespace="kitchen")),
                  path("__debug__/", include("debug_toolbar.urls")),
                  path("accounts/", include("django.contrib.auth.urls")),
              ] + static(
    settings.STATIC_URL,
    document_root=settings.STATIC_ROOT
)

kitchen/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class DishType(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        verbose_name = "DishType"
        verbose_name_plural = "DishTypes"
        ordering = ["name"]

    def __str__(self):
        return self.name


class Cook(AbstractUser):
    years_of_experience = models.IntegerField(null=True, blank=True)

    class Meta:
        verbose_name = "Cook"
        verbose_name_plural = "Cooks"
        ordering = ["username"]

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"


class Dish(models.Model):
    name = models.CharField(max_length=255, unique=True)
    description = models.TextField()
    price = models.DecimalField(max_digits=7, decimal_places=2)
    dish_type = models.ForeignKey(DishType, on_delete=models.CASCADE)
    cooks = models.ManyToManyField(Cook, related_name="dishes")

    class Meta:
        verbose_name = "Dish"
        verbose_name_plural = "Dishes"
        ordering = ["name"]

    def __str__(self):
        return self.name

kitchen/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

from kitchen.models import Cook


class CookCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Cook
        fields = UserCreationForm.Meta.fields + (
            "years_of_experience",
            "first_name",
            "last_name",
        )

    def clean_years_of_experience(self):
        return validate_years_of_experience(
            self.cleaned_data["years_of_experience"]
        )


class CookSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by username.."})
    )


class DishSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by model.."})
    )


class DishTypeSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name.."})
    )


def validate_years_of_experience(years_of_experience: int) -> int:
    if years_of_experience < 0:
        raise ValidationError("Years of experience should be positive number")
    elif years_of_experience > 99:
        raise ValidationError("Years of experience should be less than to 100")

    return years_of_experience

kitchen/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import QuerySet
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic, View

from .forms import (
    DishTypeSearchForm,
    CookSearchForm,
    DishSearchForm,
    CookCreationForm
)
from .models import Cook, DishType, Dish


@login_required
def index(request):
    """View function for home page of site."""
    num_dishes = Dish.objects.count()
    num_dishtypes = DishType.objects.count()
    num_cooks = Cook.objects.count()

    context = {
        "num_dishes": num_dishes,
        "num_dishtypes": num_dishtypes,
        "num_cooks": num_cooks,
    }

    return render(request, "kitchen/index.html", context=context)


class CookListView(LoginRequiredMixin, generic.ListView):
    paginate_by = 3
    model = Cook

    def get_context_data(self, *, object_list=None, **kwargs) -> dict:
        context = super(CookListView, self).get_context_data(**kwargs)

        context["search_form"] = CookSearchForm

        return context

    def get_queryset(self) -> QuerySet:
        queryset = Cook.objects

        form = CookSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(
                username__icontains=form.cleaned_data["username"]
            )

        return queryset


class CookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Cook


class CookCreateView(LoginRequiredMixin, generic.CreateView):
    model = Cook
    form_class = CookCreationForm
    success_url = reverse_lazy("kitchen:index")


class CookDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Cook
    success_url = reverse_lazy("kitchen:cook-list")


class DishTypeListView(LoginRequiredMixin, generic.ListView):
    paginate_by = 3
    model = DishType
    context_object_name = "dish_type_list"
    template_name = "kitchen/dish_type_list.html"

    def get_context_data(self, *, object_list=None, **kwargs) -> dict:
        context = super(DishTypeListView, self).get_context_data(**kwargs)

        context["search_form"] = DishTypeSearchForm

        return context

    def get_queryset(self) -> QuerySet:
        queryset = DishType.objects

        form = DishTypeSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )

        return queryset


class DishTypeDetailView(LoginRequiredMixin, generic.DetailView):
    model = DishType
    context_object_name = "dish_type_detail"
    template_name = "kitchen/dish_type_detail.html"


class DishTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = DishType
    fields = "__all__"
    success_url = reverse_lazy("kitchen:dish-type-list")
    template_name = "kitchen/dish_type_form.html"


class DishTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = DishType
    fields = "__all__"
    template_name = "kitchen/dish_type_form.html"

    def get_success_url(self):
        return reverse_lazy(
            "kitchen:dish-type-detail",
            kwargs={"pk": self.kwargs["pk"]}
        )


class DishTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = DishType
    success_url = reverse_lazy("kitchen:dish-type-list")
    template_name = "kitchen/dish_type_confirm_delete.html"


class DishListView(LoginRequiredMixin, generic.ListView):
    model = Dish
    paginate_by = 3

    def get_context_data(self, *, object_list=None, **kwargs) -> dict:
        context = super(DishListView, self).get_context_data(**kwargs)

        context["search_form"] = DishSearchForm

        return context

    def get_queryset(self) -> QuerySet:
        queryset = Dish.objects.prefetch_related("dish_type")

        form = DishSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )

        return queryset


class DishDetailView(LoginRequiredMixin, generic.DetailView):
    model = Dish


class DishCreateView(LoginRequiredMixin, generic.CreateView):
    model = Dish
    fields = "__all__"
    success_url = reverse_lazy("kitchen:dish-list")


class DishUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Dish
    fields = "__all__"

    def get_success_url(self):
        return reverse_lazy(
            "kitchen:dish-detail",
            kwargs={"pk": self.kwargs["pk"]}
        )


class DishDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Dish
    success_url = reverse_lazy("kitchen:dish-list")


class ToggleAssignToDish(LoginRequiredMixin, View):

    def post(self, request, pk):
        cook = Cook.objects.get(
            id=request.user.id
        )
        if Dish.objects.get(id=pk) in cook.dishes.all():
            cook.dishes.remove(pk)
        else:
            cook.dishes.add(pk)

        return HttpResponseRedirect(
            reverse_lazy("kitchen:dish-detail", args=[pk])
        )

templates/kitchen/cook_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="not-intro">
    <h1>Delete Cook?</h1>
    <form action="" method="post" novalidate>
      {% csrf_token %}
      {{ form|crispy }}

      <input class="btn btn-danger" type="submit" value="Submit">
      <a class="btn btn-primary" href="{% url "kitchen:cook-detail" pk=cook.id %}">Cancel</a>
    </form>
  </div>
{% endblock %}

templates/kitchen/cook_detail.html
{% extends "base.html" %}

{% block content %}
  <div class="not-intro">
    <h1>Cook Detail</h1>
    <h3>Username: {{ cook.username }}</h3>
    {% if cook.last_name or cook.first_name %}
      <hr>
      <h5>Name: {% if cook.last_name %}{{ cook.last_name }}{% endif %}
        {% if cook.first_name %}{{ cook.first_name }}{% endif %}</h5>
    {% endif %}
    <hr>
    <h5>Years of experience: {{ cook.years_of_experience }}</h5>
    <hr>
    <h5>Dishes: </h5>
    {% if cook.dishes.all %}
      {% for dish in cook.dishes.all %}
        <p><a href="{% url "kitchen:dish-detail" pk=dish.id %}">{{ dish.name }}</a></p>
      {% endfor %}
    {% else %}
      <p>No dishes(</p>
    {% endif %}
    {% if user.id == cook.id %}
      <a class="btn btn-danger" href="{% url "kitchen:cook-delete" pk=cook.id %}">Delete</a>
    {% endif %}
  </div>
{% endblock %}

templates/kitchen/cook_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="not-intro">
    <h1>Registration</h1>
    <form action="" method="post" novalidate>
      {% csrf_token %}
      {{ form|crispy }}

      <input class="btn btn-primary" type="submit" value="Submit">
      <a class="btn btn-primary" href="{% url "kitchen:index" %}">Cancel</a>
    </form>
  </div>
{% endblock %}

templates/kitchen/cook_list.html
{% extends "base.html" %}

{% block content %}
  <div class="not-intro">
    <h1>Cook List</h1>
    {% if cook_list %}
      {% block search %}
        {% include "includes/search.html" %}
      {% endblock %}
      {% for cook in cook_list %}
        <li>Username: <a href="{% url "kitchen:cook-detail" pk=cook.id %}">{{ cook.username }}</a>(Years of experience: {{ cook.years_of_experience }})</li>
      {% endfor %}
    {% else %}
      <h3>No cooks(</h3>
    {% endif %}
  </div>
{% endblock %}

templates/kitchen/dish_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="not-intro">
    <h1>Delete Dish?</h1>
    <form action="" method="post" novalidate>
      {% csrf_token %}
      {{ form|crispy }}

      <input class="btn btn-danger" type="submit" value="Submit">
      <a class="btn btn-primary" href="{% url "kitchen:dish-detail" pk=dish.id %}">Cancel</a>
    </form>
  </div>
{% endblock %}

templates/kitchen/dish_detail.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="not-intro">
    <h1>Dish Detail</h1>
    <h3>Name: {{ dish.name }}</h3>
    <hr>
    <h5>Price: {{ dish.price }}</h5>
    <hr>
    <h5>Dish type: {{ dish.dish_type.name }}</h5>
    <hr>
    <h5>Description: </h5>
    <p>{{ dish.description }}</p>
    <hr>
    <h5>Cooks: </h5>
    {% for cook in dish.cooks.all %}
      <p><a href="{% url "kitchen:cook-detail" pk=cook.id %}">{{ cook.username }}</a></p>
    {% endfor %}
    <form action="{% url "kitchen:toggle-assign-to-dish" pk=dish.id %}" method="post">
      {% csrf_token %}
      {{ form|crispy }}
      {% if dish in user.dishes.all %}
        <br>

        <input type="submit" value="Delete me from this dish" class="btn btn-danger">
      {% else %}
        <br>
        <input type="submit" value="Assign me to this dish" class="btn btn-primary">
      {% endif %}
    </form>
    <br>
    <a class="btn btn-primary" href="{% url "kitchen:dish-update" pk=dish.id %}">Update</a>
    <a class="btn btn-danger" href="{% url "kitchen:dish-delete" pk=dish.id %}">Delete</a>
  </div>
{% endblock %}

templates/kitchen/dish_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="not-intro">
    <h1>{{ object|yesno:"Update,Create" }} Dish</h1>
    <form action="" method="post" novalidate>
      {% csrf_token %}
      {{ form|crispy }}

      <input class="btn btn-primary" type="submit" value="Submit">
      <a class="btn btn-primary" {% if object %} href="{% url "kitchen:dish-detail" pk=dish.id %}" {% else %}href="{% url "kitchen:dish-list" %}" {% endif %}>Cancel</a>
    </form>
  </div>
{% endblock %}

templates/kitchen/dish_list.html
{% extends "base.html" %}

{% block content %}
  <div class="not-intro">
    <h1>Dish List <a href="{% url "kitchen:dish-create" %}">+</a></h1>
    {% if dish_list %}
      {% block search %}
        {% include "includes/search.html" %}
      {% endblock %}
      {% for dish in dish_list %}
        <li>Name: <a href="{% url "kitchen:dish-detail" pk=dish.id %}">{{ dish.name }}</a> Price: {{ dish.price }}(Dish type: {{ dish.dish_type.name }})</li>
      {% endfor %}
    {% else %}
      <h3>No dishes(</h3>
    {% endif %}
  </div>
{% endblock %}

templates/kitchen/dish_type_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="not-intro">
    <h1>Delete Dish type?</h1>
    <form action="" method="post" novalidate>
      {% csrf_token %}
      {{ form|crispy }}

      <input class="btn btn-danger" type="submit" value="Submit">
      <a class="btn btn-primary" href="{% url "kitchen:dish-type-detail" pk=dishtype.id %}">Cancel</a>
    </form>
  </div>
{% endblock %}

templates/kitchen/dish_type_delete.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Delete Dish type?</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input class="btn btn-danger" type="submit" value="Submit">
    <a class="btn btn-primary" href="{% url "kitchen:dish-types-detail" pk=dishtype.id %}">Cancel</a>
  </form>
{% endblock %}

templates/kitchen/dish_type_detail.html
{% extends "base.html" %}

{% block content %}
  <div class="not-intro">
    <h1>Dish type Detail</h1>
    <h3>Name: {{ dish_type_detail.name }}</h3>
    <a class="btn btn-primary" href="{% url "kitchen:dish-type-update" pk=dish_type_detail.id %}">Update</a>
    <a class="btn btn-danger" href="{% url "kitchen:dish-type-delete" pk=dish_type_detail.id %}">Delete</a>
  </div>
{% endblock %}

templates/kitchen/dish_type_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="not-intro">
    <h1>{{ object|yesno:"Update,Create" }} Dish type</h1>
    <form action="" method="post" novalidate>
      {% csrf_token %}
      {{ form|crispy }}

      <input class="btn btn-primary" type="submit" value="Submit">
      <a class="btn btn-primary" {% if object %} href="{% url "kitchen:dish-type-detail" pk=dishtype.id %}" {% else %}href="{% url "kitchen:dish-type-list" %}" {% endif %}>Cancel</a>
    </form>
  </div>
{% endblock %}

templates/kitchen/dish_type_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="not-intro">
    <h1>Dish Type List <a href="{% url "kitchen:dish-type-create" %}">+</a></h1>
    {% if dish_type_list %}
      {% block search %}
        {% include "includes/search.html" %}
      {% endblock %}
      {% for dish_type in dish_type_list %}
        <li>Name: <a href="{% url "kitchen:dish-type-detail" pk=dish_type.id %}">{{ dish_type.name }}</a></li>
      {% endfor %}
    {% else %}
      <h3>No dish types(</h3>
    {% endif %}
  </div>
{% endblock %}

templates/kitchen/index.html
{% extends "base.html" %}

{% block content %}
  <div class="intro">
    <h1>Kitchen Service</h1>
  </div>
  <div class="achievements">
    <div class="work">
      {{ num_cooks }}
      <a class="work-heading" href="cook_list.html">Cooks</a>
      <p class="work-text">We have a great team of cooks</p>
    </div>
    <div class="work">
      {{ num_dishes }}
      <a class="work-heading" href="dish_list.html">Dishes</a>
      <p class="work-text">We have a great dishes</p>
    </div>
    <div class="work">
      {{ num_dishtypes }}
      <a class="work-heading" href="dish_type_list.html">Dish Types</a>
      <p class="work-text">We have a great dish types</p>
    </div>
  </div>
{% endblock %}